---
- name: Configure MySQL on Linux source
  hosts: linux_source
  become: yes
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create a test database
      mysql_db:
        name: test_db
        state: present
        login_user: root
        login_password: "securepassword123"

    - name: Create a test user
      mysql_user:
        name: test_user
        password: "userpassword123"
        priv: "test_db.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "securepassword123"
